#!/bin/bash
# Calculate coverage for pre-defined intervals in all sorted bam files
#  requires that windows.bed file has already been generated by bedtools makewindows (see README)

# Set variables
INTERVAL_FILE="03_genome/windows.bed"

# Calculate bedtools coverage for each sorted bam
for file in $(ls -1 04_samples/*.sorted.bam)
do
    # Reporting
    echo "Calculating coverage for: " $file

    # Calculate coverage
    bedtools coverage -a $INTERVAL_FILE -b $file > "${file%.sorted.bam}"_cov.txt 

done

